#!/usr/bin/env bash
# play-confirm.sh -- play a confirmation sound on successful clipboard copy.
#
# Owned by clipso. Sounds live in the clipso config dir, one WAV per
# sequence number (1.wav, 2.wav, ...). Each call plays the NEXT sound in
# order, wrapping to 1 after the last -- a deterministic loop. The last
# played number is kept in .last alongside the sounds.
#
# Sounds are NOT versioned: they are generated by sounds/generate.sh from
# the .abc sources in the repo (miau-dio renders them).
#
# CONTRACT: _play_confirm ALWAYS returns 0. The clipboard copy has already
# succeeded by the time it runs; a missing sound or player must never turn
# a successful copy into a failure (clipso runs under `set -e`).
#
# Usage:
#   source play-confirm.sh     # defines _play_confirm, _play_special, _play_numbered
#   play-confirm.sh            # rotation (same as _play_confirm)
#   play-confirm.sh <N>        # play <N>.wav directly, bypassing the rotation
#   play-confirm.sh <name>     # play specials/<name>.wav
# When invoked directly, CLIP_ENV is auto-detected if the caller did not set it.

CLIPSO_SOUNDS_DIR="${CLIPSO_SOUNDS_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/clipso/sounds}"

# _clipso_player -- first available WAV player on this system.
_clipso_player() {
    for _c in paplay play aplay mpv; do
        command -v "$_c" >/dev/null 2>&1 && { printf '%s\n' "$_c"; return 0; }
    done
    return 1
}

# _play_file <path> -- play a WAV in the background; always returns 0.
# Never blocks the shell, never fails the caller (clipso runs under set -e).
_play_file() {
    local file="$1"
    [ -f "$file" ] || {
        printf '[WARN] play-confirm: no such sound: %s\n' "$file" >&2
        return 0
    }
    local player
    player="$(_clipso_player)" || {
        printf '[WARN] play-confirm: no audio player (paplay/play/aplay/mpv)\n' >&2
        return 0
    }
    case "$player" in
        paplay) setsid "$player" "$file" >/dev/null 2>&1 & ;;
        play)   setsid "$player" -q "$file" >/dev/null 2>&1 & ;;
        aplay)  setsid "$player" -q "$file" >/dev/null 2>&1 & ;;
        mpv)    setsid "$player" --no-video --really-quiet "$file" >/dev/null 2>&1 & ;;
    esac
    disown 2>/dev/null || true
    return 0
}

# _play_confirm -- play the next sound in the rotation, wrapping at the end.
# Advances the counter stored in .last.
_play_confirm() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0

    [ -d "$CLIPSO_SOUNDS_DIR" ] || {
        printf '[WARN] play-confirm: no sounds dir at %s\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_files=$(ls "$CLIPSO_SOUNDS_DIR"/[0-9]*.wav 2>/dev/null | sort -V)
    [ -n "$_pc_files" ] || {
        printf '[WARN] play-confirm: no sounds in %s (run: sounds/generate.sh)\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_last_file="$CLIPSO_SOUNDS_DIR/.last"
    _pc_last=$(cat "$_pc_last_file" 2>/dev/null || printf '0')

    _pc_next=""
    for _pc_f in $_pc_files; do
        _pc_n=$(basename "$_pc_f" .wav)
        if [ "$_pc_n" -gt "$_pc_last" ] 2>/dev/null; then
            _pc_next="$_pc_f"
            _pc_next_n="$_pc_n"
            break
        fi
    done
    if [ -z "$_pc_next" ]; then
        _pc_next=$(printf '%s\n' "$_pc_files" | head -1)
        _pc_next_n=$(basename "$_pc_next" .wav)
    fi

    _play_file "$_pc_next"
    printf '%s\n' "$_pc_next_n" > "$_pc_last_file"
    return 0
}

# _play_numbered <N> -- play <sounds-dir>/<N>.wav directly, bypassing rotation.
_play_numbered() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0
    _play_file "$CLIPSO_SOUNDS_DIR/${1}.wav"
}

# _play_special <name> -- play <sounds-dir>/specials/<name>.wav, no rotation.
_play_special() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0
    _play_file "$CLIPSO_SOUNDS_DIR/specials/${1}.wav"
}

# Dispatcher when invoked directly (not sourced):
#   play-confirm.sh          rotation (same as _play_confirm)
#   play-confirm.sh <N>      numbered WAV (bypass rotation)
#   play-confirm.sh <name>   specials/<name>.wav
if [ "${BASH_SOURCE[0]:-$0}" = "$0" ]; then
    if [ -z "${CLIP_ENV:-}" ]; then
        # Resolve the symlink: play-confirm is installed as ~/.local/bin/play-confirm,
        # so dirname(BASH_SOURCE) would point at the bin dir, not the repo.
        _pc_self="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || printf '%s' "${BASH_SOURCE[0]}")"
        _pc_dir="$(cd "$(dirname "$_pc_self")" && pwd)"
        [ -f "$_pc_dir/lib/core.sh" ]      && source "$_pc_dir/lib/core.sh"
        [ -f "$_pc_dir/lib/clipboard.sh" ] && source "$_pc_dir/lib/clipboard.sh"
        CLIP_ENV="$(detect_env 2>/dev/null || echo osc52)"
    fi
    case "${1:-}" in
        "")       _play_confirm ;;
        *[!0-9]*) _play_special "$1" ;;
        *)        _play_numbered "$1" ;;
    esac
fi
