#!/usr/bin/env bash
# play-confirm.sh -- play a confirmation sound on successful clipboard copy.
#
# Owned by clipso. Sounds live in the clipso config dir, one WAV per
# sequence number (1.wav, 2.wav, ...). Each call plays the NEXT sound in
# order, wrapping to 1 after the last -- a deterministic loop. The last
# played number is kept in .last alongside the sounds.
#
# Sounds are NOT versioned: they are generated by sounds/generate.sh from
# the .abc sources in the repo (miau-dio renders them).
#
# CONTRACT: _play_confirm ALWAYS returns 0. The clipboard copy has already
# succeeded by the time it runs; a missing sound or player must never turn
# a successful copy into a failure (clipso runs under `set -e`).
#
# Usage:
#   source play-confirm.sh     # defines _play_confirm, _play_special, _play_numbered
#   play-confirm.sh            # rotation (same as _play_confirm)
#   play-confirm.sh <N>        # play <N>.wav directly, bypassing the rotation
#   play-confirm.sh <name>     # play specials/<name>.wav
# When invoked directly, CLIP_ENV is auto-detected if the caller did not set it.

CLIPSO_SOUNDS_DIR="${CLIPSO_SOUNDS_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/clipso/sounds}"

# Player subsystem. Two files:
#   player       one line: the resolved player name. Cached so the
#                capability probe runs at most once per environment
#                change, not on every sound.
#   player.log   stdout+stderr of the LAST player invocation. Truncated
#                on every launch so it always describes a single attempt.
#                Kept out of /dev/null on purpose: if the sound does not
#                come out, the reason is one `cat` away.
CLIPSO_CACHE_DIR="${CLIPSO_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/clipso}"
CLIPSO_PLAYER_CACHE="$CLIPSO_CACHE_DIR/player"
CLIPSO_PLAYER_LOG="$CLIPSO_CACHE_DIR/player.log"

# Every candidate this module knows about, in preference order.
# Preference is "best integration for the environment"; usability is
# decided at runtime by _clipso_player_usable. Adding a new player means
# appending here and teaching _clipso_player_usable about it.
_CLIPSO_PLAYER_CANDIDATES="play-audio paplay play aplay mpv"

# _clipso_player_present <name> -- binary on PATH.
_clipso_player_present() {
    command -v "$1" >/dev/null 2>&1
}

# _clipso_player_usable <name> -- present AND able to play right now.
#
# Presence is not enough. paplay is on PATH on Termux yet fails with
# "Connection refused" because the PulseAudio daemon does not publish a
# native protocol socket to the unprivileged user. Playing a silent
# probe would be worse (a beep on every startup); checking the daemon
# through pactl answers the same question without side effects.
#
# Each player's "am I usable" question is answered by the cheapest test
# its environment exposes:
#   play-audio  Termux AudioTrack wrapper, no daemon in the middle:
#               presence is the whole question.
#   paplay      PulseAudio client; requires the daemon to be reachable.
#               pactl (same package) is the standard reachability probe.
#               If pactl is absent, assume the daemon setup is minimal
#               and let presence decide.
#   play/aplay  Local audio devices, no daemon: presence is the answer.
#   mpv         Broadly available fallback: presence is the answer.
_clipso_player_usable() {
    _clipso_player_present "$1" || return 1
    case "$1" in
        paplay)
            if command -v pactl >/dev/null 2>&1; then
                pactl info >/dev/null 2>&1
            else
                return 0
            fi
            ;;
        *)
            return 0
            ;;
    esac
}

# _clipso_player_diagnose -- explain, per candidate, why none is usable.
# Only called when the whole list failed; on the happy path nothing is
# printed.
_clipso_player_diagnose() {
    printf '[WARN] play-confirm: no usable audio player on this system\n' >&2
    for _c in $_CLIPSO_PLAYER_CANDIDATES; do
        if ! _clipso_player_present "$_c"; then
            printf '[WARN]   %-10s not on PATH\n' "$_c" >&2
        elif ! _clipso_player_usable "$_c"; then
            printf '[WARN]   %-10s present but unusable (probe failed)\n' "$_c" >&2
        fi
    done
    printf '[WARN]   on Termux: pkg install termux-api   (provides play-audio)\n' >&2
    printf '[WARN]   on Linux:  check the audio daemon: pactl info\n' >&2
    printf '[WARN]   log:       %s\n' "$CLIPSO_PLAYER_LOG" >&2
}

# _clipso_player -- resolve once, cache the winner.
#
# The cached name is trusted only if the probe still passes: an
# environment change (daemon stopped, package removed) invalidates the
# cache and a fresh probe runs. In steady state this is one file read
# per sound, no subprocess.
_clipso_player() {
    local _p_cached
    _p_cached="$(cat "$CLIPSO_PLAYER_CACHE" 2>/dev/null || true)"
    if [ -n "$_p_cached" ] && _clipso_player_usable "$_p_cached"; then
        printf '%s\n' "$_p_cached"
        return 0
    fi

    local _p_name
    for _p_name in $_CLIPSO_PLAYER_CANDIDATES; do
        if _clipso_player_usable "$_p_name"; then
            mkdir -p "$CLIPSO_CACHE_DIR" 2>/dev/null || true
            printf '%s\n' "$_p_name" > "$CLIPSO_PLAYER_CACHE" 2>/dev/null || true
            printf '%s\n' "$_p_name"
            return 0
        fi
    done
    return 1
}

# _play_file <path> -- play a WAV in the background; always returns 0.
#
# Never blocks the shell, never fails the caller (clipso runs under
# set -e). The player's own stdout and stderr go to $CLIPSO_PLAYER_LOG,
# truncated on every launch: one file, always describing the last
# attempt. Not /dev/null, because the reason a silent sound happened is
# exactly what we want preserved. The happy path writes nothing to the
# terminal.
_play_file() {
    local file="$1"
    [ -f "$file" ] || {
        printf '[WARN] play-confirm: no such sound: %s\n' "$file" >&2
        return 0
    }

    local player
    if ! player="$(_clipso_player)"; then
        _clipso_player_diagnose
        return 0
    fi

    mkdir -p "$CLIPSO_CACHE_DIR" 2>/dev/null || true
    : > "$CLIPSO_PLAYER_LOG" 2>/dev/null || true

    case "$player" in
        play-audio) setsid play-audio "$file" >>"$CLIPSO_PLAYER_LOG" 2>&1 & ;;
        paplay)     setsid paplay     "$file" >>"$CLIPSO_PLAYER_LOG" 2>&1 & ;;
        play)       setsid play       "$file" >>"$CLIPSO_PLAYER_LOG" 2>&1 & ;;
        aplay)      setsid aplay      "$file" >>"$CLIPSO_PLAYER_LOG" 2>&1 & ;;
        mpv)        setsid mpv --no-video "$file" >>"$CLIPSO_PLAYER_LOG" 2>&1 & ;;
    esac
    disown 2>/dev/null || true
    return 0
}

# _play_confirm -- play the next sound in the rotation, wrapping at the end.
# Advances the counter stored in .last.
_play_confirm() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0

    [ -d "$CLIPSO_SOUNDS_DIR" ] || {
        printf '[WARN] play-confirm: no sounds dir at %s\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_files=$(ls "$CLIPSO_SOUNDS_DIR"/[0-9]*.wav 2>/dev/null | sort -V)
    [ -n "$_pc_files" ] || {
        printf '[WARN] play-confirm: no sounds in %s (run: sounds/generate.sh)\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_last_file="$CLIPSO_SOUNDS_DIR/.last"
    _pc_last=$(cat "$_pc_last_file" 2>/dev/null || printf '0')

    _pc_next=""
    for _pc_f in $_pc_files; do
        _pc_n=$(basename "$_pc_f" .wav)
        if [ "$_pc_n" -gt "$_pc_last" ] 2>/dev/null; then
            _pc_next="$_pc_f"
            _pc_next_n="$_pc_n"
            break
        fi
    done
    if [ -z "$_pc_next" ]; then
        _pc_next=$(printf '%s\n' "$_pc_files" | head -1)
        _pc_next_n=$(basename "$_pc_next" .wav)
    fi

    _play_file "$_pc_next"
    printf '%s\n' "$_pc_next_n" > "$_pc_last_file"
    return 0
}

# _play_numbered <N> -- play <sounds-dir>/<N>.wav directly, bypassing rotation.
_play_numbered() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0
    _play_file "$CLIPSO_SOUNDS_DIR/${1}.wav"
}

# _play_special <name> -- play <sounds-dir>/specials/<name>.wav, no rotation.
_play_special() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0
    _play_file "$CLIPSO_SOUNDS_DIR/specials/${1}.wav"
}

# Dispatcher when invoked directly (not sourced):
#   play-confirm.sh          rotation (same as _play_confirm)
#   play-confirm.sh <N>      numbered WAV (bypass rotation)
#   play-confirm.sh <name>   specials/<name>.wav
if [ "${BASH_SOURCE[0]:-$0}" = "$0" ]; then
    if [ -z "${CLIP_ENV:-}" ]; then
        # Resolve the symlink: play-confirm is installed as ~/.local/bin/play-confirm,
        # so dirname(BASH_SOURCE) would point at the bin dir, not the repo.
        _pc_self="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || printf '%s' "${BASH_SOURCE[0]}")"
        _pc_dir="$(cd "$(dirname "$_pc_self")" && pwd)"
        [ -f "$_pc_dir/lib/core.sh" ]      && source "$_pc_dir/lib/core.sh"
        [ -f "$_pc_dir/lib/clipboard.sh" ] && source "$_pc_dir/lib/clipboard.sh"
        CLIP_ENV="$(detect_env 2>/dev/null || echo osc52)"
    fi
    _pc_arg="${1:-}"
    case "$_pc_arg" in
        "")     _play_confirm ;;
        specials/*) _play_special "${_pc_arg#specials/}" ;;
        *[!0-9]*)   _play_special "$_pc_arg" ;;
        *)
            if [ -f "$CLIPSO_SOUNDS_DIR/${_pc_arg}.wav" ]; then
                _play_numbered "$_pc_arg"
            elif [ -f "$CLIPSO_SOUNDS_DIR/specials/${_pc_arg}.wav" ]; then
                _play_special "$_pc_arg"
            else
                printf '[WARN] play-confirm: no such sound: %s\n' "$_pc_arg" >&2
            fi
            ;;
    esac
fi
