#!/usr/bin/env bash
# play-confirm.sh -- play a confirmation sound on successful clipboard copy.
#
# Owned by clipso. Sounds live in the clipso config dir, one WAV per
# sequence number (1.wav, 2.wav, ...). Each call plays the NEXT sound in
# order, wrapping to 1 after the last -- a deterministic loop. The last
# played number is kept in .last alongside the sounds.
#
# Sounds are NOT versioned: they are generated by sounds/generate.sh from
# the .abc sources in the repo (miau-dio renders them).
#
# CONTRACT: _play_confirm ALWAYS returns 0. The clipboard copy has already
# succeeded by the time it runs; a missing sound or player must never turn
# a successful copy into a failure (clipso runs under `set -e`).
#
# Usage:
#   source play-confirm.sh   # defines _play_confirm; caller invokes it
#   ./play-confirm.sh        # runs _play_confirm now (CLIP_ENV must be set)

CLIPSO_SOUNDS_DIR="${CLIPSO_SOUNDS_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/clipso/sounds}"

# _clipso_player -- first available WAV player on this system.
_clipso_player() {
    for _c in paplay play aplay mpv; do
        command -v "$_c" >/dev/null 2>&1 && { printf '%s\n' "$_c"; return 0; }
    done
    return 1
}

# _play_confirm -- play the next sound in the sequence, wrapping at the end.
# Always returns 0; audio problems are warnings only.
_play_confirm() {
    [ "${CLIP_ENV:-}" = "termux" ] || return 0

    [ -d "$CLIPSO_SOUNDS_DIR" ] || {
        printf '[WARN] play-confirm: no sounds dir at %s\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_files=$(ls "$CLIPSO_SOUNDS_DIR"/[0-9]*.wav 2>/dev/null | sort -V)
    [ -n "$_pc_files" ] || {
        printf '[WARN] play-confirm: no sounds in %s (run: clipso sounds)\n' "$CLIPSO_SOUNDS_DIR" >&2
        return 0
    }

    _pc_last_file="$CLIPSO_SOUNDS_DIR/.last"
    _pc_last=$(cat "$_pc_last_file" 2>/dev/null || printf '0')

    _pc_next=""
    for _pc_f in $_pc_files; do
        _pc_n=$(basename "$_pc_f" .wav)
        if [ "$_pc_n" -gt "$_pc_last" ] 2>/dev/null; then
            _pc_next="$_pc_f"
            _pc_next_n="$_pc_n"
            break
        fi
    done
    if [ -z "$_pc_next" ]; then
        _pc_next=$(printf '%s\n' "$_pc_files" | head -1)
        _pc_next_n=$(basename "$_pc_next" .wav)
    fi

    _pc_player=$(_clipso_player) || {
        printf '[WARN] play-confirm: no audio player (paplay/play/aplay/mpv)\n' >&2
        return 0
    }

    # Play in the background: the confirmation sound must never block the
    # shell -- the user keeps typing while it plays. setsid detaches it from
    # the controlling terminal; disown keeps it out of the shell job table.
    case "$_pc_player" in
        paplay) setsid "$_pc_player" "$_pc_next" >/dev/null 2>&1 & ;;
        play)   setsid "$_pc_player" -q "$_pc_next" >/dev/null 2>&1 & ;;
        aplay)  setsid "$_pc_player" -q "$_pc_next" >/dev/null 2>&1 & ;;
        mpv)    setsid "$_pc_player" --no-video --really-quiet "$_pc_next" >/dev/null 2>&1 & ;;
    esac
    disown 2>/dev/null || true

    printf '%s\n' "$_pc_next_n" > "$_pc_last_file"
    return 0
}

if [ "${BASH_SOURCE[0]:-$0}" = "$0" ]; then
    _play_confirm
fi
